name: CI - Maven TestNG with Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Maven Tests
        id: run_tests
        run: mvn clean test

      - name: Extract Failed Test Names
        if: always()
        run: |
          mkdir -p tmp
          if [ -f test-output/testng-results.xml ]; then
            grep -oP '(?<=<test-method status="FAIL" name=")[^"]+' test-output/testng-results.xml > tmp/failed_tests.txt || true
          else
            echo "No testng-results.xml found" > tmp/failed_tests.txt
          fi

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            test-output/**
            reports/**/*.html

      - name: Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if grep -q FAIL tmp/failed_tests.txt; then
            STATUS="FAILURE"
            ICON=":x:"
          else
            STATUS="SUCCESS"
            ICON=":white_check_mark:"
          fi

          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          MESSAGE="$ICON CI $STATUS - [View Run]($RUN_URL)"

          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"$MESSAGE\"}" \
               "$SLACK_WEBHOOK_URL"
