name: CI - Maven TestNG with Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Run Maven Tests
        id: run_tests
        run: mvn clean test
        continue-on-error: true

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            test-output/**
            reports/**/*.html

      - name: Slack Notification
        if: always()
        run: |
          STATUS="SUCCESS"
          ICON=":white_check_mark:"
          if [ "${{ steps.run_tests.outcome }}" != "success" ]; then
            STATUS="FAILURE"
            ICON=":x:"
          fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$ICON CI $STATUS - [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
