name: CI - Maven TestNG with Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Run Maven Tests
        id: run_tests
        run: mvn clean test || true  # ensures workflow continues even if tests fail

      - name: Extract Failed Test Names
        if: always()
        run: |
          mkdir -p tmp
          if [ -f test-output/testng-results.xml ]; then
            grep -oP '(?<=<test-method status="FAIL" name=")[^"]+' test-output/testng-results.xml > tmp/failed_tests.txt || true
          else
            echo "No testng-results.xml found" > tmp/failed_tests.txt
          fi

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            test-output/**
            reports/**/*.html

      - name: Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="SUCCESS"
          ICON=":white_check_mark:"
          FAIL_DETAILS=""
          if [ "${{ steps.run_tests.outcome }}" != "success" ]; then
            STATUS="FAILURE"
            ICON=":x:"
            if [ -s tmp/failed_tests.txt ]; then
              FAIL_DETAILS="\n*Failed Tests:* $(tr '\n' ', ' < tmp/failed_tests.txt)"
            else
              FAIL_DETAILS="\nNo failed test details found."
            fi
          fi

          MESSAGE="$ICON CI $STATUS in *${{ github.repository }}* on branch *${{ github.ref_name }}*.
<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run Logs>$FAIL_DETAILS"

          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"$MESSAGE\"}" \
               "$SLACK_WEBHOOK_URL"
