name: CI - Maven TestNG with Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Maven Tests
        id: run_tests
        run: |
          mkdir -p tmp
          mvn clean test || true  # continue even if tests fail

      - name: Upload Reports and Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-output/**
            reports/**
            screenshots/**
            tmp/**

      - name: Slack Notification with Screenshot
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="${{ steps.run_tests.outcome }}"
          ICON=":white_check_mark:"
          if [ "$STATUS" != "success" ]; then
            ICON=":x:"
            STATUS="FAILURE"
          else
            STATUS="SUCCESS"
          fi

          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          MESSAGE="$ICON CI $STATUS - <${RUN_URL}|View Run>"

          if [ -f tmp/screenshot-path.txt ]; then
            SCREENSHOT=$(ls screenshots/*.png | head -1)
            curl -F file=@"$SCREENSHOT" -F "initial_comment=$MESSAGE" -F channels="#your-channel-name" -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" https://slack.com/api/files.upload
          else
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" "$SLACK_WEBHOOK_URL"
          fi
